name: Build Kivy APK

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Corrigir permissões do .git
      - name: Corrigir permissões do .git
        run: sudo chown -R $USER:$USER .git

      # Cache Buildozer, Gradle e dependências do Gradle
      - name: Cache buildozer and gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.gradle/caches
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # (Opcional) Limpar cache manualmente se necessário
      # - name: Limpar cache (opcional)
      #   run: rm -rf ~/.buildozer ~/.gradle

      # Instalar Cython e atualizar pip para evitar warnings de language level
      - name: Instalar Cython e atualizar pip
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade cython

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: src
          # Remover --depend '"androidx.core:core:1.6.0"' se estiver no buildozer.spec
          command: buildozer android debug

      - name: Mostrar log do Buildozer se falhar
        if: failure()
        run: |
          echo "==== Buildozer LOG ===="
          cat src/.buildozer/android/platform/build-arm64-v8a/dists/estoqueapp/buildozer.log || echo "Log não encontrado"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: src/bin/*.apk
